source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby ">= 3.0.0"

gem "rails", "~> 7.1.3"
gem "puma", "~> 6.4"
gem "redis", "~> 5.1"
gem "rack-cors"
gem "dotenv-rails"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[ windows jruby ]
